name: .NET Framework CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v1

    - name: Install NuGet dependencies
      run: nuget restore GitActionsTester.sln

    - name: Build project
      run: msbuild GitActionsTester.sln /p:Configuration=Release

    # Optional test step if there are tests defined in your project
    # - name: Run tests
    #   run: vstest.console.exe "**\*.Test.dll" --logger:trx
